### ISSUE TITLE
Can it provide :TransparentToggle ?

### ISSUE THREAD

**Issue by Freed-Wu** [Kjwon15/vim-transparent#1]
it will be more convenient. thanks!

**Comment by Kjwon15** [comment]
I think it can be implemented by Disable/Enable and reload current colour scheme

**Comment by Freed-Wu** [comment]
`:TransparentToggle` will execute `:TransparentEnable` and `:TransparentDisable` alternatively, i think. really?

**Comment by Kjwon15** [comment]
Implemented at 8d99cc2756518e00d38dcad19c90126ffca1a4fa
